#!/bin/bash

source "${BASH_SOURCE%/*}/common.sh"

function install() {
    echo "Installing AWS CLI..."
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip awscliv2.zip
    sudo ./aws/install
    rm -r aws
    rm awscliv2.zip
    pushd /tmp || exit

    # Enabling Bash autocompletion
    echo "complete -C /usr/local/bin/aws_completer aws" >~/.config/bashrc.d/aws_completer.sh

    # Enabling Zsh autocompletion
    cat <<EOF >~/.config/zshrc.d/aws_completer.sh
autoload bashcompinit && bashcompinit
autoload -Uz compinit && compinit
complete -C '/usr/local/bin/aws_completer' aws
EOF
}

function uninstall() {
    echo "Uninstalling AWS CLI..."
    sudo rm /usr/local/bin/aws
    sudo rm /usr/local/bin/aws_completer
    sudo rm -rf /usr/local/aws-cli
    rm ~/.config/bashrc.d/aws_completer.sh
    rm ~/.config/zshrc.d/aws_completer.sh
}

main $1
