#!/bin/bash
######################################################################################
# Installs tools for AWS development
#
# Components installed:
#   - AWS CLI 2
#   - AWS Session Manager Plugin
#
# Configuration
#   - ~/.config/bashrc.d/aws_completer.sh - AWS auto completion for Bash
#   - ~/.config/zshrc.d/aws_completer.sh  - AWS Auto completion for Zsh
#   - ~/.ssh/config.d/aws.config          - Ability to SSH into EC2s with instance ID
#
######################################################################################

source "${BASH_SOURCE%/*}/common.sh"

function install_aws_session_manager_plugin() {
    # Install the SSM Agent
    #
    # Instructions were adapted from https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-working-with-install-plugin.html
    #
    curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "/tmp/session-manager-plugin.deb"
    sudo dpkg -i /tmp/session-manager-plugin.deb
    rm /tmp/session-manager-plugin.deb
}

function uninstall_aws_session_manager_plugin() {
    sudo dpkg -r session-manager-plugin
}

function upgrade_aws_session_manager_plugin() {
    uninstall_aws_session_manager_plugin
    install_aws_session_manager_plugin    
}

function install_aws_cli() {
    echo "Installing AWS CLI..."
    pushd /tmp || exit
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip awscliv2.zip
    sudo ./aws/install
    rm -r aws
    rm awscliv2.zip
    popd
}

function uninstall_aws_cli() {
    echo "Uninstalling AWS CLI..."
    sudo rm /usr/local/bin/aws
    sudo rm /usr/local/bin/aws_completer
    sudo rm -rf /usr/local/aws-cli
}

function upgrade_aws_cli() {
    echo "Upgrading AWS CLI..."
    pushd /tmp || exit
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip awscliv2.zip
    sudo ./aws/install --upgrade
    rm -r aws
    rm awscliv2.zip
    popd
}

function install_aws_autocomplete() {
    # Enabling Bash autocompletion
    echo "complete -C /usr/local/bin/aws_completer aws" >~/.config/bashrc.d/aws_completer.sh

    # Enabling Zsh autocompletion
    cat <<EOF >~/.config/zshrc.d/aws_completer.sh
autoload bashcompinit && bashcompinit
autoload -Uz compinit && compinit
complete -C '/usr/local/bin/aws_completer' aws
EOF
}

function uninstall_aws_autocomplete() {
    rm ~/.config/bashrc.d/aws_completer.sh
    rm ~/.config/zshrc.d/aws_completer.sh
}

function install() {
    install_aws_cli
    install_aws_autocomplete
    install_aws_session_manager_plugin
}

function uninstall() {
    uninstall_aws_cli
    uninstall_aws_autocomplete
    uninstall_aws_session_manager_plugin
}

function upgrade() {
    upgrade_aws_cli
    upgrade_aws_session_manager_plugin
}

main $1
