#!/bin/bash

function install() {
    echo "Installing NVM..."
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
    
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

    nvm install --lts

    if which code; then
        echo "Installing VSCode plugin..."
       code --install-extension Swellaby.node-pack --force
    else
       echo "Visual Studio code was not found, skipping plugin installation."
    fi
}

function uninstall() {
    echo "Uninstalling NVM and all NVM-managed runtimes..."

    if [[ -d ~/.nvm ]]; then
        echo "Removing ~/.nvm"
        rm -rf ~/.nvm
    fi

    if which code; then
       echo "Removing VSCode plugin"
       code --uninstall-extension Swellaby.node-pack --force
    else
       echo "Visual Studio code was not found, skipping plugin uninstall."
    fi
}

if [[ $1 == "install" ]]; then
    install
elif [[ $1 == "uninstall" ]]; then
    uninstall
else
    echo "Usage: rust-installer {install|uninstall}"
fi
