#!/bin/bash

source "${BASH_SOURCE%/*}/common.sh"

VSCODE_EXTENSION="Swellaby.node-pack"

function install() {
    echo "Installing NVM..."
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
    
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

    nvm install --lts

    install_vscode_extension "${VSCODE_EXTENSION}"
}

function uninstall() {
    echo "Uninstalling NVM and all NVM-managed runtimes..."

    if [[ -d ~/.nvm ]]; then
        echo "Removing ~/.nvm"
        rm -rf ~/.nvm
    fi
    uninstall_vscode_extension "${VSCODE_EXTENSION}"
}

main $1
