#!/bin/bash
######################################################################################
# Installs the Julia development environment
#
# Components installed:
#   - Juliaup (https://github.com/JuliaLang/juliaup)
#   - Latest Julia version
#   - Julia kernel for Jupyter
#
######################################################################################

source "${BASH_SOURCE%/*}/common.sh"

function install_julia() {
    # Install Juliaup
    curl -fsSL https://install.julialang.org | sh

    # Install the IJulia kernel for Jupyter
    ~/.juliaup/bin/julia - <<EOF
using Pkg
Pkg.add("IJulia")
EOF

    install_vscode_extension julialang.language-julia
}

function uninstall_julia() {
    juliaup self uninstall
    uninstall_vscode_extension julialang.language-julia
}

function install() {
    install_julia
}

function uninstall() {
    uninstall_julia
}

function upgrade() {
    echo "Done"
}

main $1
