#!/bin/bash
######################################################################################
# Installs Notebook software
#
# Components installed:
#   - Jupyter
#   - VSCode Jupyter extensions (to let VSCode use Jupyter kernels)
#
# Notes
#   - The Jupyter packages and kernels are installed using pip --user in the user's
#     home directory. This leads to more than 250 MB of Python packages are installed
#     which are hard to uninstall and maintain. A better segregation of the Jupyter
#     environment is required without installing Jupyter in each virtual env.
#
######################################################################################

source "${BASH_SOURCE%/*}/common.sh"

#
# Jupyter main
#
function install_jupyter() {
    pip install --user jupyter
}

function upgrade_jupyter() {
    pip install -U jupyter
}

function install_jupyter_vscode_extension() {
    install_vscode_extension ms-toolsai.jupyter
}

function uninstall_jupyter_vscode_extension() {
    uninstall_vscode_extension ms-toolsai.jupyter
}

function install() {
    install_jupyter
    install_jupyter_vscode_extension
}

function uninstall() {
    uninstall_vscode_extension
}

function upgrade() {
    upgrade_jupyter
}

main $1
