#!/bin/bash

source "${BASH_SOURCE%/*}/common.sh"

VSCODE_EXTENSION="ms-kubernetes-tools.vscode-kubernetes-tools"

#
# Installs k3s.
#
function install_k3s() {
    echo "Installing k3s..."
    curl -sfL https://get.k3s.io | sudo sh -
}

function uninstall_k3s() {
    echo "Uninstalling K3s..."
    sudo k3s-uninstall.sh
}

function install_minikube() {
    echo "Installing Minikube..."
    pushd /tmp || exit
    curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    sudo mv minikube-linux-amd64 /usr/local/bin/minikube
    sudo chmod 755 /usr/local/bin/minikube
    popd || exit

    mkdir -p ~/.config/bashrc.d
    mkdir -p ~/.config/zshrc.d
    echo "source <(minikube completion zsh)" >~/.config/zshrc.d/minikube_completion.sh
    echo "source <(minikube completion bash)" >~/.config/bashrc.d/minikube_completion.sh
}

function uninstall_minikube() {
    echo "Uninstalling Minikube..."
    rm ~/.config/bashrc.d/minikube_completion.sh
    rm ~/.config/zshrc.d/minikube_completion.sh    
    sudo rm /usr/local/bin/minikube
}

function install_k3d() {
    echo "Installing K3d..."
    curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash

    mkdir -p ~/.config/bashrc.d
    mkdir -p ~/.config/zshrc.d
    echo "source <(k3d completion bash)" >~/.config/bashrc.d/k3d_completion.sh
    echo "source <(k3d completion zsh)" >~/.config/zshrc.d/k3d_completion.sh
}

function uninstall_k3d() {
    echo "Uninstalling K3d..."
    rm ~/.config/bashrc.d/k3d_completion.sh
    rm ~/.config/zshrc.d/k3d_completion.sh    
    sudo rm /usr/local/bin/k3d
}

function install() {
    # Local K8s development is much easier with a containerized distro like
    # Minikube or K3s. Direct install of K3s is disabled by default. Uncomment
    # to install.
    #
    # install_k3s

    install_minikube
    install_k3d

    # 
    # Installing kubectl
    #
    sudo curl -fsSLo /etc/apt/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
    echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
    sudo apt update
    sudo apt install -y kubectl

    # Installing kubectl autocomplete
    mkdir -p ~/.config/bashrc.d
    mkdir -p ~/.config/zshrc.d
    echo "source <(kubectl completion bash)" >~/.config/bashrc.d/kubectl_completion.sh
    echo "source <(kubectl completion zsh)" >~/.config/zshrc.d/kubectl_completion.sh

    #
    # Installing kubectx and kubens
    #
    pushd /tmp || exit
    mkdir -p ~/.local/bin
    wget https://github.com/ahmetb/kubectx/releases/download/v0.9.4/kubectx_v0.9.4_linux_x86_64.tar.gz
    tar xvzf kubectx_v0.9.4_linux_x86_64.tar.gz
    mv kubectx ~/.local/bin
    rm kubectx_v0.9.4_linux_x86_64.tar.gz

    wget https://github.com/ahmetb/kubectx/releases/download/v0.9.4/kubens_v0.9.4_linux_x86_64.tar.gz
    tar xvzf kubens_v0.9.4_linux_x86_64.tar.gz
    mv kubens ~/.local/bin
    rm kubens_v0.9.4_linux_x86_64.tar.gz

    popd || exit

    # 
    # Installing Helm
    #
    curl -fsSL https://baltocdn.com/helm/signing.asc | sudo gpg --dearmor -o /etc/apt/keyrings/helm.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
    sudo apt update
    sudo apt install helm

    install_vscode_extension "${VSCODE_EXTENSION}"
}

function uninstall() {
    # K3s is not installed by default. Uncomment to uninstall it.
    #
    # uninstall_k3s

    uninstall_k3d
    uninstall_minikube

    # Uninstalling kubectl autocomplete
    rm ~/.config/bashrc.d/kubectl_completion.sh
    rm ~/.config/zshrc.d/kubectl_completion.sh

    #
    # Uninstalling kubectl
    #
    sudo apt -y remove kubectl
    sudo rm /etc/apt/sources.list.d/kubernetes.list
    sudo rm /etc/apt/keyrings/kubernetes-archive-keyring.gpg

    #
    # Removing kubectx and kubens
    #
    rm ~/.local/bin/kubectx
    rm ~/.local/bin/kubens

    #
    # Uninstalling Helm    
    #
    sudo apt -y remove helm
    sudo rm /etc/apt/sources.list.d/helm-stable-debian.list
    sudo rm /etc/apt/keyrings/helm.gpg        

    uninstall_vscode_extension "${VSCODE_EXTENSION}"
}

main $1
