#!/bin/bash

source "${BASH_SOURCE%/*}/common.sh"

VSCODE_EXTENSION="rust-lang.rust-analyzer"

function install() {
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

    install_vscode_extension "${VSCODE_EXTENSION}"
}

function uninstall() {
    echo "Uninstalling Rust..."

    rustup self uninstall

    uninstall_vscode_extension "${VSCODE_EXTENSION}"
}

main $1
