#!/bin/bash

source ./common.sh

VSCODE_EXTENSION="rust-lang.rust-analyzer"

function install() {
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

    install_vscode_extension "${VSCODE_EXTENSION}"
}

function uninstall() {
    echo "Uninstalling Rust..."

    if [[ -d ~/.rustup ]]; then
        echo "Removing ~/.rustup"
        rm -r ~/.rustup
    fi

    if [[ -d ~/.cargo ]]; then
        echo "Removing ~/.cargo"
        rm -r ~/.cargo
    fi    

    uninstall_vscode_extension "${VSCODE_EXTENSION}"
}

main $1
