#!/bin/bash

source "${BASH_SOURCE%/*}/common.sh"

function install() {
    sudo apt-get install -y shellcheck

    install_vscode_extension timonwong.shellcheck
    install_vscode_extension rogalmic.bash-debug
}

function uninstall() {
    echo "Uninstalling shellcheck..."

    sudo apt-get remove -y shellcheck

    uninstall_vscode_extension rogalmic.bash-debug
    uninstall_vscode_extension timonwong.shellcheck
}

main $1
