#!/bin/bash
#
# This script installs all the general purpose applications that I use
# for everyday workflows. They may not be related to software development.
# The applications range from command line utilities to GUI applications. 
# 

#
# This script assumes that the following dependencies are already installed.
# - curl and related packages
# - Git tooling (Git credential manager, GitHub CLI)
# - Python runtime environment including pyenv, pipx, etc.
# - General purpose utilities: jq, yq
#

#
# Things which shuld not be installed using this script
# - Editor (emacs, vim, vscode)
# - Project management utiltities (ep, crp, cdp, etc.)
#

source "${BASH_SOURCE%/*}/common.sh"

PACKAGES="exa htop mc ncdu powerline stow tmux"

function install() {
    # Installation steps are added from https://www.terraform.io/downloads

    # Installing utilities
    sudo apt-get update
    sudo apt-get install -y ${PACKAGES}

    #
    # Configure Git if not running in a Dev Container.
    # Note: Visual Studio Code's dev container implementation will copy the
    #       host's ~/.gitconfig to the container if there is no existing file
    #       on the container. The command below would create one, leading to
    #       the container not inheriting the parent credentials and settings. 
    #
    if [[ "$REMOTE_CONTAINERS" != "true" ]]; then
        git config --global init.defaultBranch main
    fi
    
    #
    # Install js-shell-lib with its dependencies.
    #    
    bash -c "$(curl -fsSL https://raw.githubusercontent.com/sandor-juhasz/js-shell-lib/main/install)"

    #
    # PlantUML support
    #
    # install_vscode_extension jebbs.plantuml
}

# function uninstall() {
#     sudo apt -y remove ${PACKAGES}

#     if is_wsl; then
#         echo "VSCode should not be installed in the WSL distro. Doing nothing..."
#     else
#         sudo apt remove code
#         sudo rm /etc/apt/sources.list.d/vscode.list
#         sudo rm /etc/apt/keyrings/packages.microsoft.gpg
#         sudo apt update
#     fi

#     uninstall_cookiecutter    

#     uninstall_vscode_extension jebbs.plantuml
# }

main $1
