#!/bin/bash
#
# This script installs all those general purpose applications that are needed
# for everyday software development workflows. The applications range from 
# command line utilities to GUI applications. 
# 
# The only common in them is that they cannot be tied to any single development
# platform but can be used by all of them.
#

source "${BASH_SOURCE%/*}/common.sh"

PACKAGES="curl emacs git htop mc ncdu powerline stow tmux vim-gtk3 zsh"

function install_vscode() {
    # Installation steps are added from https://www.terraform.io/downloads

    # Installing prerequisites
    sudo apt-get update   
    sudo apt-get -y install ca-certificates curl gnupg lsb-release

    # Installing Docker's official GPG key
    sudo mkdir -p /etc/apt/keyrings
    curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --dearmor -o /etc/apt/keyrings/packages.microsoft.gpg

    # Setting up the repository
    echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" | sudo tee /etc/apt/sources.list.d/vscode.list

    # Installing Terraform
    sudo apt-get update 
    sudo apt-get -y install code
}

function uninstall_vscode() {
    echo "Uninstalling Visual Studio Code..."
    sudo apt-get -y remove code
    sudo rm /etc/apt/sources.list.d/vscode.list
    sudo rm /etc/apt/keyrings/packages.microsoft.gpg
    sudo apt-get update
}


function install() {
    sudo apt-get -y install ${PACKAGES}
    install_vscode
}

function uninstall() {
    sudo apt-get -y remove ${PACKAGES}
    uninstall vscode
}

main $1
