#!/bin/bash
#
# This script installs all those general purpose applications that are needed
# for everyday software development workflows. The applications range from 
# command line utilities to GUI applications. 
# 
# The only common in them is that they cannot be tied to any single development
# platform but can be used by all of them.
#

source "${BASH_SOURCE%/*}/common.sh"

PACKAGES="curl emacs git htop mc ncdu powerline stow tmux vim-gtk3 zsh"

function install() {
    # Installation steps are added from https://www.terraform.io/downloads

    # Installing prerequisites
    sudo apt -y install ca-certificates curl gnupg lsb-release
    sudo apt update 
    sudo apt -y install ${PACKAGES}

    if grep -q Microsoft /proc/version; then
        echo "VSCode should not be installed in the WSL distro. Skipping this step..."
    else
        echo "Not WSL distro, installing VSCode."
        # Installing Microsoft's official GPG key
        if [[ ! -e /etc/apt/keyrings/packages.microsoft.gpg ]]; then
            sudo mkdir -p /etc/apt/keyrings
            curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --dearmor -o /etc/apt/keyrings/packages.microsoft.gpg
        fi

        # Setting up the repository
        if [[ ! -e /etc/apt/sources.list.d/vscode.list ]]; then
            echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" | sudo tee /etc/apt/sources.list.d/vscode.list
        fi

        sudo apt update
        sudo apt -y install code
    fi
}

function uninstall() {
    sudo apt -y remove ${PACKAGES}

    if grep -q Microsoft /proc/version; then
        echo "VSCode should not be installed in the WSL distro. Doing nothing..."
    else
        sudo apt remove code
        sudo rm /etc/apt/sources.list.d/vscode.list
        sudo rm /etc/apt/keyrings/packages.microsoft.gpg
        sudo apt update
    fi
}

main $1
